version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: bank-card-management
    restart: always
    environment:
      POSTGRES_DB: card_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"